# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  # Pods for LoginUI

end
